[pytest]
markers =
    login: marks tests related to login functionality
    cart: marks tests related to cart functionality
    checkout: marks tests related to checkout functionality
    logout: marks tests related to logout functionality
    smoke: marks smoke tests (critical path)
    regression: marks regression tests