name: Selenium Tests

on:
  push:
    branches:
      - main
      - feature/cicd
      - feature/additional-tests
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Set up Chrome
        uses: browser-actions/setup-chrome@v1

      - name: Run Selenium Tests
        run: |
          cd "Selenium TestScripts using python and Pytest"
          pytest -v
        env:
          DISPLAY: :99